POST http://localhost:3000/colaborador
Content-Type: application/json

{
  "nome": "João da Silva",
  "status": "Ativo",
  "email": "joao.silva@example.com",
  "uidMSK": "XYZ789",
  "password": "senha123",
  "type": "default",
  "localidade": "SSZ",
  "brand": "Brand X",
  "jobTitle": "Motorista",
  "cpf": "12345678901",
  "usaEstacionamento": true,
  "cidadeEstacionamento": "Santos",
  "cnh": "CNH987654",
  "tipoCNH": "A"
}

###

GET https://bck8ksw0kkw0csckkoo8gcgk.212.85.1.115.sslip.io/colaboradores

###

GET http://localhost:3000/colaborador/1

###

GET https://bck8ksw0kkw0csckkoo8gcgk.212.85.1.115.sslip.io/colaborador/JSI123

###

PUT http://localhost:3000/api/colaborador/1
Content-Type: application/json

{
  "nome": "João da Silva"
}


###

DELETE http://localhost:3000/colaborador/12