POST http://localhost:3000/historico
Content-Type: application/json

{
  "colaboradorUid": "XYZ789",
  "veiculoId": 1,
  "dataInicio": "2023-10-01T00:00:00Z",
  "dataFim": "2023-10-10T00:00:00Z",
  "tipoUso": "temporário"
}

###

GET https://bck8ksw0kkw0csckkoo8gcgk.212.85.1.115.sslip.io/historicos

###

GET http://localhost:3000/historico/1

###

PUT http://localhost:3000/historico/1
Content-Type: application/json

{
  "dataFim": "2023-10-15T00:00:00Z",
  "tipoUso": "permanente"
}

###

DELETE http://localhost:3000/historico/1

###

POST https://bck8ksw0kkw0csckkoo8gcgk.212.85.1.115.sslip.io/historico-utilizacao/iniciar
Content-Type: application/json

{
  "placa": "HIJ4567",
  "modelo": "Modelo Teste",
  "renavam": "123456789",
  "chassi": "1234567890",
  "status": "disponivel"
}

###

POST https://bck8ksw0kkw0csckkoo8gcgk.212.85.1.115.sslip.io/historico-utilizacao/finalizar
Content-Type: application/json

{
  "placa": "HIJ4567",
  "colaboradorUid": "JSI123"
}