GET https://bck8ksw0kkw0csckkoo8gcgk.212.85.1.115.sslip.io/dashboard-metrics

###

GET http://localhost:3000/dashboard-metrics-colaborador-maior-aumento

###

GET http://localhost:3000/top-offenders

###

GET http://localhost:3000/veiculos-devolucao

###

GET http://localhost:3000/vencimento-multas

###

GET https://bck8ksw0kkw0csckkoo8gcgk.212.85.1.115.sslip.io/infracoes-chart-data