POST http://localhost:3000/veiculo
Content-Type: application/json

{
  "fornecedor": "Fornecedor X",
  "contrato": "ContratoXYZ",
  "placa": "ABC-1234",
  "renavam": "REN12345678",
  "chassi": "CHAS1234567890",
  "modelo": "Modelo A",
  "cor": "Preto",
  "status": "Disponível",
  "cliente": "Cliente Y",
  "perfil": "Perfil A",
  "centroCusto": "Centro A",
  "franquiaKM": 1000,
  "carroReserva": false,
  "dataDisponibilizacao": "2025-03-01T00:00:00Z",
  "mesesContratados": 12,
  "previsaoDevolucao": "2026-03-01T00:00:00Z",
  "mesesFaltantes": 6,
  "mensalidade": 1500.00,
  "budget": 2000.00,
  "multa": 300.00,
  "proximaRevisao": "2025-06-01T00:00:00Z"
}

###

GET http://localhost:3000/veiculos

###

GET http://localhost:3000/veiculo/ABC1234/qrcode.svg

###

GET http://localhost:3000/veiculo/1

###

GET http://localhost:3000/veiculo/ABC-1234

###

PUT http://localhost:3000/veiculo/1
Content-Type: application/json

{
  "fornecedor": "Localiza"
}

###

DELETE http://localhost:3000/veiculo/1