GET http://localhost:3000/dashboard-metrics

###

GET http://localhost:3000/dashboard-metrics-colaborador-maior-aumento

###

GET http://localhost:3000/top-offenders

###

GET http://localhost:3000/veiculos-manutencao

###

GET http://localhost:3000/vencimento-multas

###

GET http://localhost:3000/infracoes-chart-data