POST http://localhost:3000/infracao
Content-Type: application/json

{
  "tipo": "multa",
  "placa": "ABC1234",
  "colaboradorUid": "JSI123",
  "veiculoId": 1,
  "costCenter": "Centro 1",
  "dataInfracao": "2025-03-15T00:00:00Z",
  "tag": "TAG001",
  "hora": "08:30",
  "valor": 150.00,
  "prefixo": "PFX001",
  "marca": "Marca A",
  "categoria": "Categoria A",
  "rodovia": "Rodovia 1",
  "praca": "Praça 1"
}

###

POST http://localhost:3000/infracao
Content-Type: application/json

{
  "tipo": "sem parar",
  "placa": "DEF5678",
  "colaboradorUid": "MOL456",
  "veiculoId": 2,
  "costCenter": "Centro 2",
  "dataInfracao": "2025-03-15T00:00:00Z",
  "tag": "TAG001",
  "hora": "08:30",
  "valor": 35.50,
  "prefixo": "PFX001",
  "marca": "Marca A",
  "categoria": "Categoria A",
  "rodovia": "Rodovia 1",
  "praca": "Praça 1"
}

###

GET http://localhost:3000/infracoes

###

GET http://localhost:3000/infracao/1

###

PUT http://localhost:3000/infracao/1
Content-Type: application/json

{
  "statusResposta": "Respondido",
  "reconhecimento": true
}

###

DELETE http://localhost:3000/infracao/1