POST http://localhost:3000/usuario
Content-Type: application/json

{
  "email": "user@example.com",
  "uidMSK": "ABC123",      
  "password": "123456",
  "type": "default"
}

###

GET http://localhost:3000/usuarios

###

GET http://localhost:3000/usuario/ABC123

###

PUT http://localhost:3000/usuario/ABC123
Content-Type: application/json

{
  "password": "newpassword",
  "type": "adm"
}

###

DELETE http://localhost:3000/usuario/ABC123